runs:
  using: "composite"
  steps:
    - run: corepack enable
      shell: bash
    - uses: actions/setup-node@v6
      with:
        node-version-file: ".node-version"
        cache: "pnpm"
    - run: pnpm install
      shell: bash
